### ISSUE TITLE
Change Name

### ISSUE THREAD

**Issue by PhoenixPeca** [PHProxy/phproxy#11]
Hi @miglen,
I think it would be better to rename this repository to something that's different than "PHProxy". Apparently the original PHProxy has gained enough forks that was named similarly to the original one, which is kind of confusing. The original project was abandoned quite some time ago, as we all know it; This fact itself gives the impression to the users that this fork is no longer maintained and/or is an unmodified copy of the original project.

**Comment by PhoenixPeca** [comment]
What do you think @boppy? 😄

**Comment by miglen** [comment]
I disagree. I like the fact that the project can keep up living with the same name. Let's improve it, it has a lot of things to be done.

**Comment by PhoenixPeca** [comment]
So be it 😄
