### ISSUE TITLE
Sometimes, Facebook Just Don't Cooperate

### ISSUE THREAD

**Issue by PhoenixPeca** [PHProxy/phproxy#18]
![image](https://user-images.githubusercontent.com/9730242/40001304-8a0670a2-57c0-11e8-97b9-6a2ba9e192c0.png)

This happens because facebook left a `p` tag unclosed somewhere within its html structure. While this may not be a problem for most websites as browsers nowadays are smart enough to ignore the error and render the page properly, this is not the case with facebook as some of its pages were rendered in `application/xhtml+xml` content-type, which is a strict type of markup language. This results in an error such as seen from the image above.

**Comment by PhoenixPeca** [comment]
this is a website specific fix.

**Comment by biojet1** [comment]
nice
