### ISSUE TITLE
something error?

### ISSUE THREAD

**Issue by d9394** [PHProxy/phproxy#19]
I download v1.1.0.tar.gz and put it to my openwrt router with PHP Version 5.6.17 installed, and then, I use FF to open "http://192.168.1.1/phproxy-1.1.0/index.php" ,and the result is : Parse error: syntax error, unexpected '{' in /usr/html/phproxy/index.php on line 889
So, how can I do now ?

**Comment by d9394** [comment]
I am sure when I was browser with phpinfo(), my router php is running OK.

**Comment by PhoenixPeca** [comment]
can you please email me aspaciop(at)phoenixpeca(dot)com

**Comment by Toantruong** [comment]
I reproduced this issue and fixed it at line 889:
      if (trim($attrs['action']) === '' || trim($attrs['action']){0} === '#')
--> if (trim($attrs['action']) === '' || trim($attrs['action'])[0] === '#')

Please update the index.php and re-run again

**Comment by PhoenixPeca** [comment]
Thank you! :)
