### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by stampylongr** [PHProxy/phproxy#20]
Parse error: syntax error, unexpected '{' in /home/cabox/workspace/phproxy/index.php on line 896

**Comment by PhoenixPeca** [comment]
Hi can you please add a detail about what version are you using? are you using the master branch?

**Comment by PhoenixPeca** [comment]
![image](https://user-images.githubusercontent.com/9730242/46839954-223d7480-cdf3-11e8-99b3-e2599d3001b4.png)

Everything seems to be working fine for me. 

Please provide your PHP version; The PHProxy version you are using; and the steps to reproduce the problem. 😄
