### ISSUE TITLE
Better interface

### ISSUE THREAD

**Issue by miglen** [PHProxy/phproxy#4]
Modernize the interface to be more responsive and mobile friendly.

**Comment by boppy** [comment]
As a huge fan of PHProxy for years I'm happy to see the project is up again.

I just made a little CSS-Update (had to change some Markup as well) to discuss about.

Please leave comments. I would really like to finish this work and make it a PR.

PS: As I had no idea about the base color I used the one from @miglen s Website ;) Can be changed by just changing L7 in style.less and recompile.

**Comment by PhoenixPeca** [comment]
I have already implemented this feature. I'm closing this now.
