### ISSUE TITLE
Is This Repo Still Active?

### ISSUE THREAD

**Issue by PhoenixPeca** [PHProxy/phproxy#8]
Hi @miglen,
I am planning on continuing this project and so far, I have fixed many regex bugs that renders some ~modern~ websites broken... Are you still into this project?

**Comment by miglen** [comment]
Hey yeah this repo is alive. If you want to contribute I can add you to the
github org. You are very welcome!

**Comment by PhoenixPeca** [comment]
That would be great!! ❤️

**Comment by PhoenixPeca** [comment]
I'll be opening pull requests this following hours. 😉 I would love to merge them myself when I'm in the organization. Thanks!
